### ISSUE TITLE
P115 devices names replaced with "Device Tapo"

### ISSUE THREAD

**Issue by Robi1021** [tnmendes/watt#73]
Using Tapo P115 devices, which have assigned names (e.g. living room lamp)
After some time these names got „lost“ in Watt & the device appear under the name „Device Tapo“.
(Imagine how hard it will be to find the right one, if you make use of several P115 devices)
![55DD56D6-918A-464C-A35F-13A3A8020FA5](https://user-images.githubusercontent.com/92546958/188269838-4313b987-8ba9-4e13-8498-9591b158fd45.jpeg)
![9059F173-B347-4C7C-BD9D-D77BEE464FFA](https://user-images.githubusercontent.com/92546958/188269840-59d6eb34-7ad4-456f-9496-fbc67589e901.jpeg)

**Comment by tnmendes** [comment]
Hey @Robi1021, it's the first time I'm seeing this problem.

this is what I have in my code:

`if(modelEnum.getBrand() == .tapo) {
            alias = alias.base64Decoded() ?? "Device Tapo"
        }`
        
For some reason, the decode of the alias that is in Base64 is not working for 3 devices, so when it fails I am setting "Device Tapo"
Are all your P115s on the same firmware version?

**Comment by Robi1021** [comment]
Hey @tnmendes 
Yes they have all the same firmware & hardware revisions 
Strange part is, that this „issue“ occur sporadically.
I did a reset of the Watt app & include the tapos new , which result in working as expected for a few days until the „issue“ is reoccurring.

From what I observed, it may fix itself after some time/days, but didn’t stay stable.
![EC6D1404-B249-4FEA-8B7C-E37A916F31EB](https://user-images.githubusercontent.com/92546958/188277600-4ecc8d75-2a87-4000-b55c-e9140221ccb7.jpeg)

**Comment by robertybob** [comment]
I too am having this issue. It’s reassuring that I’m not the only one :)

**Comment by tnmendes** [comment]
I still couldn't understand why this is happening, from my analysis randomly the Tp-Link servers do not send the device name, and Watt when the name is missing replaces it with the default name "Device Tapo".
Even with the new firmware this still happens, I really don't understand why :-/

**Comment by tnmendes** [comment]
I've managed to solve the problem, I'm making a new request to get the settings and the device name is always correct there.
Download the latest version 4.5.7 (when downloading pay attention to the version, because I sent 2 versions in the last 24 hours)
If everything is in order I will close this issue.

**Comment by rhencullen** [comment]
It looks like after the recent update to fix the "Device-Tapo" naming issue, almost all P110 Tapo devices are now showing as "Nickname-Tapo" unfortunately.

 ![image](https://user-images.githubusercontent.com/9452729/198813649-555f1f8b-9652-4172-8d41-ff904dfe48f6.jpeg)

**Comment by Robi1021** [comment]
Looks promising to me with the actual updated version 4.5.7
Will monitor it the next days

**Comment by robertybob** [comment]
Still having this issue on the latest version

**Comment by tnmendes** [comment]
Hey guys new version is available Watt 4.5.9 this update should fix the issue that some users are having.

For some reason, anyone who buys a new Tapo device is using other new Tapo servers.
Something strange that I noticed is that even though I am in Europe, Tapo is setting my server as default to the USA.

**Comment by rhencullen** [comment]
It’s still the same here unfortunately,  4.5.9 still showing Nickname Tapo for around a third to half the tapo devices.—-On 8 Nov 2022, at 17:49, Tiago Mendes ***@***.***> wrote:﻿
Hey guys new version is available Watt 4.5.9 this update should fix the issue that some users are having.
For some reason, anyone who buys a new Tapo device is using other new Tapo servers.
Something strange that I noticed is that even though I am in Europe, Tapo is setting my server as default to the USA.

**Comment by robertybob** [comment]
Working fine for me now, many thanks!

**Comment by rhencullen** [comment]
Perhaps it’s a P110 specific issue, as all of the Tapo devices here are P110 variants.—-On 8 Nov 2022, at 17:49, Tiago Mendes ***@***.***> wrote:﻿
Hey guys new version is available Watt 4.5.9 this update should fix the issue that some users are having.
For some reason, anyone who buys a new Tapo device is using other new Tapo servers.
Something strange that I noticed is that even though I am in Europe, Tapo is setting my server as default to the USA.

**Comment by robertybob** [comment]
> Perhaps it’s a P110 specific issue, as all of the Tapo devices here are P110 variants.—-On 8 Nov 2022, at 17:49, Tiago Mendes ***@***.***> wrote:﻿ Hey guys new version is available Watt 4.5.9 this update should fix the issue that some users are having. For some reason, anyone who buys a new Tapo device is using other new Tapo servers. Something strange that I noticed is that even though I am in Europe, Tapo is setting my server as default to the USA. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

I had two P110 models with this issue, now fixed, strange that you’re still having the issue  :(

**Comment by rhencullen** [comment]
It’s never gone here unfortunately, it improved a little with the last update, but I still had around a quarter of the Tapo devices with the ‘Nickname” name, and while the specific devices affected have changed now and then, overall there’s around a third to a quarter of 20+ devices without the correct name.—-On 15 Nov 2022, at 18:56, robertybob ***@***.***> wrote:﻿
Ok the issue has come back :(

**Comment by tnmendes** [comment]
With this new version of Watt 5.0.0 is this problem still happening?

**Comment by robertybob** [comment]
Working fine for me now 

> With this new version of Watt 5.0.0 is this problem still happening?

**Comment by rhencullen** [comment]
It’s looking okay here for me at the moment.Had issues with the later point releases for v4, but V5 is looking a lot better.Paul—-On 6 Feb 2023, at 16:08, Tiago Mendes ***@***.***> wrote:﻿
With this new version of Watt 5.0.0 is this problem still happening?
